// app/layout.tsx or layout.jsx (depending on your setup)

import "./globals.css";


// ✅ Import Poppins font
import { Poppins } from "next/font/google";
import { Footer } from "@/components/Footer";
import Topbar from "@/components/Topbar";
import MedicineCategoryNav from "@/components/Navbar";


// ✅ Load the font with desired weights and subsets
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose weights as needed
  variable: "--font-poppins", // Optional: useful if using CSS variables
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Topbar/>
        <MedicineCategoryNav/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
